### ISSUE TITLE
Not specified default values should be updated with default from template

### ISSUE THREAD

**Issue by timofurrer** [Roche/foxops#108]
If a default value is left empty it is rendered in the `.fengine.yaml` like all the other variables. When the template version is updated the default values from those template variables are never used in the update.

A possible solution may be to make the variables in the `.fengine.yaml` an object with a flag indicated if the value came from the template default or not (for backwards compatibility a simple string should also be parsable and should in that case fengine should behave as of right now.)

**Comment by defreng** [comment]
fixed by #427
