### ISSUE TITLE
If the incarnation project was existing in gitlab, foxops UI should support create a new incarnation for it

### ISSUE THREAD

**Issue by feiyunzhou** [Roche/foxops#118]
A gitlab project has been created, and I want to use foxops to manage to incarnate it, then I tried to create a incarnation using the foxops console, but the foxops threw errors like "Incarnation at '/a/b/c' and target directory './' already initialized"

**Comment by defreng** [comment]
actually - it's already possible via the API.

you can call the 'create incarnation` API with an `allow_import` URL parameter.
