### ISSUE TITLE
file for directory can be create by condition?

### ISSUE THREAD

**Issue by chimisu** [Roche/foxops#323]
I have a file,expression is like: `{% if deploy_mode == "offline" %}cdp-stages.yaml{% endif %}`,when deploy_mode is not offline,foxops got a error: `IsADirectoryError: [Errno 21] Is a directory: '/tmp/tmpyqebbanc'`

does this expresion is allowed in file name?or you have another solution.

**Comment by defreng** [comment]
Hi @chimisu 

I understand that you only want to create this file if the expression is true?
In this case I would rather suggest to always create the file, but wrap the entire contents in the if condition you mentioned - such that it will just be empty if it is not needed
