### ISSUE TITLE
file or directory can be control by jinja2 expression?

### ISSUE THREAD

**Issue by chimisu** [Roche/foxops#324]
I have a file,expression is like: `{% if deploy_mode == "offline" %}cdp-stages.yaml{% endif %}`,when deploy_mode is not offline,foxops got a error: `IsADirectoryError: [Errno 21] Is a directory: '/tmp/tmpyqebbanc'`

does this expresion is allowed in file name?or you have another solution.

**Comment by chimisu** [comment]
<img width="646" alt="image" src="https://github.com/Roche/foxops/assets/12495369/71acbf7e-baaa-4a84-b869-9b672e7dfb08">

**Comment by chimisu** [comment]
<img width="612" alt="image" src="https://github.com/Roche/foxops/assets/12495369/f2fa897e-558f-46db-9ce4-d1cc03a45cd7">

**Comment by chimisu** [comment]
when `deploy_mode="offline"`,file name is odp-stages.yaml,Otherwise file is not exist.

**Comment by defreng** [comment]
see the comment in #323 - would that help you with this issue?
