### ISSUE TITLE
gitlab race condition when automerging: Waiting for pipeline execution is skipped

### ISSUE THREAD

**Issue by defreng** [Roche/foxops#4]
when `automerge` is set to true, foxops performs a few steps in quick succession:
1. creating a branch
2. pushing commits
3. creating an MR
4. calling the Gitlab API to automerge the MR

We hit the case at least once, that this apparently triggers an internal race condition in Gitlab, where the MR was actually merge _before_ the pipeline completed, probably even before the pipeline was created/started.

To me it's unclear whether this is something we could mitigate with a small "sleep" in foxops, or if this needs to be fixed by Gitlab upstream.

**Comment by defreng** [comment]
@timofurrer didn't you recently implement a fix for this?

**Comment by timofurrer** [comment]
@defreng Yes - let's call it a "mitigation" :D
