### ISSUE TITLE
Encountered some errors when get-incarnations-by-id

### ISSUE THREAD

**Issue by feiyunzhou** [Roche/foxops#78]
Encountered "Internal server" errors when put-incarnations-by-id, see below error.  Tried again, then the issue gone.     

raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'https://[...]/api/incarnations/202'
For more information check: https://httpstatuses.com/500

**Comment by timofurrer** [comment]
@feiyunzhou can you please post the foxops logs which should contain more information about the error ...

**Comment by feiyunzhou** [comment]
This log is from nanny when I calling foxops API, so I can't get all of them.    I think this should `put` request rather than `get`. It seems that when the incarnation's status is pending, and when I put this request, there will have this error. Maybe you can help check the back-end log to confirm it.  It should return `409 Conflict` error code rather than 500 internal error.

**Comment by defreng** [comment]
Hey @feiyunzhou 

I'll close this issue for now since it didn't seem to happen anymore in recent times...
